Repository chtzou/Slug-Academic-Organizer, pull requests merged in 2018-10, with the labels that each got.

#13 Update/class schedules
  .babelrc
  api/__tests__/soe.test.js
  api/data/courses.json
  api/data/departments.json
  api/data/ge.json
  api/data/schedule.json
  api/soe.js
  client/package-lock.json
  client/package.json
  client/src/App.test.js
  data/ge.json
  data/soe.js
  data/test.js
  package-lock.json
  package.json
  server.js
Labels: enhancement

#19 Stored the JSON data into team DB
  .gitignore
  client/package.json
  client/src/App.js
  config/example_key.js
  models/Data.js
  package-lock.json
  package.json
  server.js
Labels: enhancement

#22 Removed /models folder & updated formatting
  client/package-lock.json
  client/src/index.js
  package-lock.json
  server.js
  server/models/Data.js
  server/routes/api/signin.js
Labels: invalid

#23 Created a class submission form
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/ClassInput.css
  client/src/ClassInput.js
  client/src/logo.svg
  package.json
  server.js
  server/models/classData.js
Labels: enhancement

#25 sign up and sign in properly working
  client/src/Home.js
  client/src/index.js
  package-lock.json
  package.json
  server.js
  server/routes/api/signin.js
Labels: enhancement

#33 small package.json update
  client/src/App.js
  client/src/components/ClassInput.js
  client/src/components/Error.js
  client/src/components/Home.js
  package.json
Labels: bug, enhancement
